services:
  - type: web
    name: yt-screenshot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
    plan: free
    aptPackages:
      - ffmpeg
